### ISSUE TITLE
Installing typed_dag in a Docker container bloats image

### ISSUE THREAD

**Issue by jiaweihli** [opf/typed_dag#25]
I'm creating a small rails 5.1.4 app which uses `typed_dag`.  Gems are being installed via `bundle install --without development test`.

Size of `bundle install...` command:
  - before adding `typed_dag`: 88.2MB
  - after adding `typed_dag`: 772MB

I haven't yet had time to dig in, but do you have any ideas about how to lower the extra 700MB added by `typed_dag`?

**Comment by ulferts** [comment]
@jiaweihli v2.0.2 just got released and it is considerably smaller:

![image](https://user-images.githubusercontent.com/617519/35150798-0933b3c6-fd1c-11e7-8f48-252b977b1697.png)

I also seized the opportunity to update the readme so that the requirement on the unique index is mentioned.

**Comment by jiaweihli** [comment]
Installed 2.0.2 and the size after adding `typed_dag` is...*drumroll*...88.2MB!  Meaning it's 0% bigger 😄 

Awesome, thanks for both fixes!
